sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/nim-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-base nim --version
  - docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -v "$(pwd):/project" -w /project yglukhov/nim-base sh -c "nimble install -dy && nimble tests"
