# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2016-10-20"
const awsApiMD_endpointPrefix* = "budgets"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "AWSBudgets"
const awsApiMD_serviceFullName* = "AWS Budgets"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AWSBudgetServiceGateway"
const awsApiMD_uid* = "budgets-2016-10-20"
defineClient(Budgets)
proc createBudget*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateBudget", "POST", "/", r)
proc createNotification*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateNotification", "POST", "/", r)
proc createSubscriber*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateSubscriber", "POST", "/", r)
proc deleteBudget*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteBudget", "POST", "/", r)
proc deleteNotification*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteNotification", "POST", "/", r)
proc deleteSubscriber*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteSubscriber", "POST", "/", r)
proc describeBudget*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeBudget", "POST", "/", r)
proc describeBudgets*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeBudgets", "POST", "/", r)
proc describeNotificationsForBudget*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeNotificationsForBudget", "POST", "/", r)
proc describeSubscribersForNotification*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeSubscribersForNotification", "POST", "/", r)
proc updateBudget*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateBudget", "POST", "/", r)
proc updateNotification*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateNotification", "POST", "/", r)
proc updateSubscriber*(cl: Budgets, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateSubscriber", "POST", "/", r)
