# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2017-04-28"
const awsApiMD_endpointPrefix* = "cloudhsmv2"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "CloudHSM V2"
const awsApiMD_serviceFullName* = "AWS CloudHSM V2"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_signingName* = "cloudhsm"
const awsApiMD_targetPrefix* = "BaldrApiService"
const awsApiMD_uid* = "cloudhsmv2-2017-04-28"
defineClient(CloudHSM)
proc createCluster*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateCluster", "POST", "/", r)
proc createHsm*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateHsm", "POST", "/", r)
proc deleteCluster*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteCluster", "POST", "/", r)
proc deleteHsm*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteHsm", "POST", "/", r)
proc describeBackups*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeBackups", "POST", "/", r)
proc describeClusters*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeClusters", "POST", "/", r)
proc initializeCluster*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "InitializeCluster", "POST", "/", r)
proc listTags*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTags", "POST", "/", r)
proc tagResource*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TagResource", "POST", "/", r)
proc untagResource*(cl: CloudHSM, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UntagResource", "POST", "/", r)
