# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2016-10-06"
const awsApiMD_endpointPrefix* = "codebuild"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "AWS CodeBuild"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "CodeBuild_20161006"
const awsApiMD_uid* = "codebuild-2016-10-06"
defineClient(CodeBuild)
proc batchDeleteBuilds*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "BatchDeleteBuilds", "POST", "/", r)
proc batchGetBuilds*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "BatchGetBuilds", "POST", "/", r)
proc batchGetProjects*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "BatchGetProjects", "POST", "/", r)
proc createProject*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateProject", "POST", "/", r)
proc createWebhook*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateWebhook", "POST", "/", r)
proc deleteProject*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteProject", "POST", "/", r)
proc deleteWebhook*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteWebhook", "POST", "/", r)
proc invalidateProjectCache*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "InvalidateProjectCache", "POST", "/", r)
proc listBuilds*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListBuilds", "POST", "/", r)
proc listBuildsForProject*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListBuildsForProject", "POST", "/", r)
proc listCuratedEnvironmentImages*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListCuratedEnvironmentImages", "POST", "/", r)
proc listProjects*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListProjects", "POST", "/", r)
proc startBuild*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StartBuild", "POST", "/", r)
proc stopBuild*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StopBuild", "POST", "/", r)
proc updateProject*(cl: CodeBuild, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateProject", "POST", "/", r)
