# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2017-04-19"
const awsApiMD_endpointPrefix* = "codestar"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "CodeStar"
const awsApiMD_serviceFullName* = "AWS CodeStar"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "CodeStar_20170419"
const awsApiMD_uid* = "codestar-2017-04-19"
defineClient(CodeStar)
proc associateTeamMember*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AssociateTeamMember", "POST", "/", r)
proc createProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateProject", "POST", "/", r)
proc createUserProfile*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateUserProfile", "POST", "/", r)
proc deleteProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteProject", "POST", "/", r)
proc deleteUserProfile*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteUserProfile", "POST", "/", r)
proc describeProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeProject", "POST", "/", r)
proc describeUserProfile*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeUserProfile", "POST", "/", r)
proc disassociateTeamMember*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisassociateTeamMember", "POST", "/", r)
proc listProjects*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListProjects", "POST", "/", r)
proc listResources*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListResources", "POST", "/", r)
proc listTagsForProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTagsForProject", "POST", "/", r)
proc listTeamMembers*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTeamMembers", "POST", "/", r)
proc listUserProfiles*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListUserProfiles", "POST", "/", r)
proc tagProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TagProject", "POST", "/", r)
proc untagProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UntagProject", "POST", "/", r)
proc updateProject*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateProject", "POST", "/", r)
proc updateTeamMember*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateTeamMember", "POST", "/", r)
proc updateUserProfile*(cl: CodeStar, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateUserProfile", "POST", "/", r)
