# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2012-10-29"
const awsApiMD_endpointPrefix* = "datapipeline"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_serviceFullName* = "AWS Data Pipeline"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "DataPipeline"
const awsApiMD_protocol* = "json"
const awsApiMD_uid* = "datapipeline-2012-10-29"
defineClient(DataPipeline)
proc activatePipeline*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ActivatePipeline", "POST", "/", r)
proc addTags*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddTags", "POST", "/", r)
proc createPipeline*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreatePipeline", "POST", "/", r)
proc deactivatePipeline*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeactivatePipeline", "POST", "/", r)
proc deletePipeline*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeletePipeline", "POST", "/", r)
proc describeObjects*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeObjects", "POST", "/", r)
proc describePipelines*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribePipelines", "POST", "/", r)
proc evaluateExpression*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "EvaluateExpression", "POST", "/", r)
proc getPipelineDefinition*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetPipelineDefinition", "POST", "/", r)
proc listPipelines*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListPipelines", "POST", "/", r)
proc pollForTask*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PollForTask", "POST", "/", r)
proc putPipelineDefinition*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutPipelineDefinition", "POST", "/", r)
proc queryObjects*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "QueryObjects", "POST", "/", r)
proc removeTags*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RemoveTags", "POST", "/", r)
proc reportTaskProgress*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ReportTaskProgress", "POST", "/", r)
proc reportTaskRunnerHeartbeat*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ReportTaskRunnerHeartbeat", "POST", "/", r)
proc setStatus*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "SetStatus", "POST", "/", r)
proc setTaskStatus*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "SetTaskStatus", "POST", "/", r)
proc validatePipelineDefinition*(cl: DataPipeline, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ValidatePipelineDefinition", "POST", "/", r)
