# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2017-04-19"
const awsApiMD_endpointPrefix* = "dax"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "Amazon DAX"
const awsApiMD_serviceFullName* = "Amazon DynamoDB Accelerator (DAX)"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AmazonDAXV3"
const awsApiMD_uid* = "dax-2017-04-19"
defineClient(DAX)
proc createCluster*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateCluster", "POST", "/", r)
proc createParameterGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateParameterGroup", "POST", "/", r)
proc createSubnetGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateSubnetGroup", "POST", "/", r)
proc decreaseReplicationFactor*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DecreaseReplicationFactor", "POST", "/", r)
proc deleteCluster*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteCluster", "POST", "/", r)
proc deleteParameterGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteParameterGroup", "POST", "/", r)
proc deleteSubnetGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteSubnetGroup", "POST", "/", r)
proc describeClusters*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeClusters", "POST", "/", r)
proc describeDefaultParameters*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeDefaultParameters", "POST", "/", r)
proc describeEvents*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeEvents", "POST", "/", r)
proc describeParameterGroups*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeParameterGroups", "POST", "/", r)
proc describeParameters*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeParameters", "POST", "/", r)
proc describeSubnetGroups*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeSubnetGroups", "POST", "/", r)
proc increaseReplicationFactor*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "IncreaseReplicationFactor", "POST", "/", r)
proc listTags*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTags", "POST", "/", r)
proc rebootNode*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RebootNode", "POST", "/", r)
proc tagResource*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TagResource", "POST", "/", r)
proc untagResource*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UntagResource", "POST", "/", r)
proc updateCluster*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateCluster", "POST", "/", r)
proc updateParameterGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateParameterGroup", "POST", "/", r)
proc updateSubnetGroup*(cl: DAX, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateSubnetGroup", "POST", "/", r)
