# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2012-10-25"
const awsApiMD_endpointPrefix* = "directconnect"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "AWS Direct Connect"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "OvertureService"
const awsApiMD_uid* = "directconnect-2012-10-25"
defineClient(DirectConnect)
proc allocateConnectionOnInterconnect*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AllocateConnectionOnInterconnect", "POST", "/", r)
proc allocateHostedConnection*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AllocateHostedConnection", "POST", "/", r)
proc allocatePrivateVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AllocatePrivateVirtualInterface", "POST", "/", r)
proc allocatePublicVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AllocatePublicVirtualInterface", "POST", "/", r)
proc associateConnectionWithLag*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AssociateConnectionWithLag", "POST", "/", r)
proc associateHostedConnection*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AssociateHostedConnection", "POST", "/", r)
proc associateVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AssociateVirtualInterface", "POST", "/", r)
proc confirmConnection*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ConfirmConnection", "POST", "/", r)
proc confirmPrivateVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ConfirmPrivateVirtualInterface", "POST", "/", r)
proc confirmPublicVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ConfirmPublicVirtualInterface", "POST", "/", r)
proc createBGPPeer*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateBGPPeer", "POST", "/", r)
proc createConnection*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateConnection", "POST", "/", r)
proc createDirectConnectGateway*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateDirectConnectGateway", "POST", "/", r)
proc createDirectConnectGatewayAssociation*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateDirectConnectGatewayAssociation", "POST", "/", r)
proc createInterconnect*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateInterconnect", "POST", "/", r)
proc createLag*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateLag", "POST", "/", r)
proc createPrivateVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreatePrivateVirtualInterface", "POST", "/", r)
proc createPublicVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreatePublicVirtualInterface", "POST", "/", r)
proc deleteBGPPeer*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteBGPPeer", "POST", "/", r)
proc deleteConnection*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteConnection", "POST", "/", r)
proc deleteDirectConnectGateway*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteDirectConnectGateway", "POST", "/", r)
proc deleteDirectConnectGatewayAssociation*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteDirectConnectGatewayAssociation", "POST", "/", r)
proc deleteInterconnect*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteInterconnect", "POST", "/", r)
proc deleteLag*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteLag", "POST", "/", r)
proc deleteVirtualInterface*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteVirtualInterface", "POST", "/", r)
proc describeConnectionLoa*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeConnectionLoa", "POST", "/", r)
proc describeConnections*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeConnections", "POST", "/", r)
proc describeConnectionsOnInterconnect*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeConnectionsOnInterconnect", "POST", "/", r)
proc describeDirectConnectGatewayAssociations*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeDirectConnectGatewayAssociations", "POST", "/", r)
proc describeDirectConnectGatewayAttachments*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeDirectConnectGatewayAttachments", "POST", "/", r)
proc describeDirectConnectGateways*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeDirectConnectGateways", "POST", "/", r)
proc describeHostedConnections*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeHostedConnections", "POST", "/", r)
proc describeInterconnectLoa*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeInterconnectLoa", "POST", "/", r)
proc describeInterconnects*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeInterconnects", "POST", "/", r)
proc describeLags*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeLags", "POST", "/", r)
proc describeLoa*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeLoa", "POST", "/", r)
proc describeLocations*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeLocations", "POST", "/", r)
proc describeTags*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeTags", "POST", "/", r)
proc describeVirtualGateways*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeVirtualGateways", "POST", "/", r)
proc describeVirtualInterfaces*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeVirtualInterfaces", "POST", "/", r)
proc disassociateConnectionFromLag*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisassociateConnectionFromLag", "POST", "/", r)
proc tagResource*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TagResource", "POST", "/", r)
proc untagResource*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UntagResource", "POST", "/", r)
proc updateLag*(cl: DirectConnect, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateLag", "POST", "/", r)
