# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2015-11-01"
const awsApiMD_endpointPrefix* = "discovery"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "AWS Application Discovery Service"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AWSPoseidonService_V2015_11_01"
const awsApiMD_uid* = "discovery-2015-11-01"
defineClient(Discovery)
proc associateConfigurationItemsToApplication*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AssociateConfigurationItemsToApplication", "POST", "/", r)
proc createApplication*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateApplication", "POST", "/", r)
proc createTags*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateTags", "POST", "/", r)
proc deleteApplications*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplications", "POST", "/", r)
proc deleteTags*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteTags", "POST", "/", r)
proc describeAgents*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeAgents", "POST", "/", r)
proc describeConfigurations*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeConfigurations", "POST", "/", r)
proc describeExportConfigurations*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeExportConfigurations", "POST", "/", r)
proc describeExportTasks*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeExportTasks", "POST", "/", r)
proc describeTags*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeTags", "POST", "/", r)
proc disassociateConfigurationItemsFromApplication*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisassociateConfigurationItemsFromApplication", "POST", "/", r)
proc exportConfigurations*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ExportConfigurations", "POST", "/", r)
proc getDiscoverySummary*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetDiscoverySummary", "POST", "/", r)
proc listConfigurations*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListConfigurations", "POST", "/", r)
proc listServerNeighbors*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListServerNeighbors", "POST", "/", r)
proc startDataCollectionByAgentIds*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StartDataCollectionByAgentIds", "POST", "/", r)
proc startExportTask*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StartExportTask", "POST", "/", r)
proc stopDataCollectionByAgentIds*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StopDataCollectionByAgentIds", "POST", "/", r)
proc updateApplication*(cl: Discovery, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateApplication", "POST", "/", r)
