# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2015-10-07"
const awsApiMD_endpointPrefix* = "events"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "Amazon CloudWatch Events"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AWSEvents"
const awsApiMD_uid* = "events-2015-10-07"
defineClient(Events)
proc deleteRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteRule", "POST", "/", r)
proc describeEventBus*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeEventBus", "POST", "/", r)
proc describeRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeRule", "POST", "/", r)
proc disableRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisableRule", "POST", "/", r)
proc enableRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "EnableRule", "POST", "/", r)
proc listRuleNamesByTarget*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListRuleNamesByTarget", "POST", "/", r)
proc listRules*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListRules", "POST", "/", r)
proc listTargetsByRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTargetsByRule", "POST", "/", r)
proc putEvents*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutEvents", "POST", "/", r)
proc putPermission*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutPermission", "POST", "/", r)
proc putRule*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutRule", "POST", "/", r)
proc putTargets*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutTargets", "POST", "/", r)
proc removePermission*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RemovePermission", "POST", "/", r)
proc removeTargets*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RemoveTargets", "POST", "/", r)
proc testEventPattern*(cl: Events, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TestEventPattern", "POST", "/", r)
