# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2015-08-14"
const awsApiMD_endpointPrefix* = "kinesisanalytics"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "Kinesis Analytics"
const awsApiMD_serviceFullName* = "Amazon Kinesis Analytics"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "KinesisAnalytics_20150814"
const awsApiMD_timestampFormat* = "unixTimestamp"
const awsApiMD_uid* = "kinesisanalytics-2015-08-14"
defineClient(KinesisAnalytics)
proc addApplicationCloudWatchLoggingOption*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddApplicationCloudWatchLoggingOption", "POST", "/", r)
proc addApplicationInput*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddApplicationInput", "POST", "/", r)
proc addApplicationInputProcessingConfiguration*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddApplicationInputProcessingConfiguration", "POST", "/", r)
proc addApplicationOutput*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddApplicationOutput", "POST", "/", r)
proc addApplicationReferenceDataSource*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddApplicationReferenceDataSource", "POST", "/", r)
proc createApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateApplication", "POST", "/", r)
proc deleteApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplication", "POST", "/", r)
proc deleteApplicationCloudWatchLoggingOption*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplicationCloudWatchLoggingOption", "POST", "/", r)
proc deleteApplicationInputProcessingConfiguration*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplicationInputProcessingConfiguration", "POST", "/", r)
proc deleteApplicationOutput*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplicationOutput", "POST", "/", r)
proc deleteApplicationReferenceDataSource*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteApplicationReferenceDataSource", "POST", "/", r)
proc describeApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeApplication", "POST", "/", r)
proc discoverInputSchema*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DiscoverInputSchema", "POST", "/", r)
proc listApplications*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListApplications", "POST", "/", r)
proc startApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StartApplication", "POST", "/", r)
proc stopApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StopApplication", "POST", "/", r)
proc updateApplication*(cl: KinesisAnalytics, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateApplication", "POST", "/", r)
