# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_uid* = "machinelearning-2014-12-12"
const awsApiMD_apiVersion* = "2014-12-12"
const awsApiMD_endpointPrefix* = "machinelearning"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_serviceFullName* = "Amazon Machine Learning"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AmazonML_20141212"
const awsApiMD_protocol* = "json"
defineClient(MachineLearning)
proc addTags*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "AddTags", "POST", "/", r)
proc createBatchPrediction*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateBatchPrediction", "POST", "/", r)
proc createDataSourceFromRDS*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateDataSourceFromRDS", "POST", "/", r)
proc createDataSourceFromRedshift*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateDataSourceFromRedshift", "POST", "/", r)
proc createDataSourceFromS3*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateDataSourceFromS3", "POST", "/", r)
proc createEvaluation*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateEvaluation", "POST", "/", r)
proc createMLModel*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateMLModel", "POST", "/", r)
proc createRealtimeEndpoint*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateRealtimeEndpoint", "POST", "/", r)
proc deleteBatchPrediction*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteBatchPrediction", "POST", "/", r)
proc deleteDataSource*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteDataSource", "POST", "/", r)
proc deleteEvaluation*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteEvaluation", "POST", "/", r)
proc deleteMLModel*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteMLModel", "POST", "/", r)
proc deleteRealtimeEndpoint*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteRealtimeEndpoint", "POST", "/", r)
proc deleteTags*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteTags", "POST", "/", r)
proc describeBatchPredictions*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeBatchPredictions", "POST", "/", r)
proc describeDataSources*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeDataSources", "POST", "/", r)
proc describeEvaluations*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeEvaluations", "POST", "/", r)
proc describeMLModels*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeMLModels", "POST", "/", r)
proc describeTags*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeTags", "POST", "/", r)
proc getBatchPrediction*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetBatchPrediction", "POST", "/", r)
proc getDataSource*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetDataSource", "POST", "/", r)
proc getEvaluation*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetEvaluation", "POST", "/", r)
proc getMLModel*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetMLModel", "POST", "/", r)
proc predict*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "Predict", "POST", "/", r)
proc updateBatchPrediction*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateBatchPrediction", "POST", "/", r)
proc updateDataSource*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateDataSource", "POST", "/", r)
proc updateEvaluation*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateEvaluation", "POST", "/", r)
proc updateMLModel*(cl: MachineLearning, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateMLModel", "POST", "/", r)
