# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2017-09-01"
const awsApiMD_endpointPrefix* = "mediastore"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "MediaStore"
const awsApiMD_serviceFullName* = "AWS Elemental MediaStore"
const awsApiMD_serviceId* = "MediaStore"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_signingName* = "mediastore"
const awsApiMD_targetPrefix* = "MediaStore_20170901"
const awsApiMD_uid* = "mediastore-2017-09-01"
defineClient(MediaStore)
proc createContainer*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateContainer", "POST", "/", r)
proc deleteContainer*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteContainer", "POST", "/", r)
proc deleteContainerPolicy*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteContainerPolicy", "POST", "/", r)
proc describeContainer*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeContainer", "POST", "/", r)
proc getContainerPolicy*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetContainerPolicy", "POST", "/", r)
proc listContainers*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListContainers", "POST", "/", r)
proc putContainerPolicy*(cl: MediaStore, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "PutContainerPolicy", "POST", "/", r)
