# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2014-05-15"
const awsApiMD_endpointPrefix* = "route53domains"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "Amazon Route 53 Domains"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "Route53Domains_v20140515"
const awsApiMD_uid* = "route53domains-2014-05-15"
defineClient(Route53Domains)
proc checkDomainAvailability*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CheckDomainAvailability", "POST", "/", r)
proc checkDomainTransferability*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CheckDomainTransferability", "POST", "/", r)
proc deleteTagsForDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteTagsForDomain", "POST", "/", r)
proc disableDomainAutoRenew*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisableDomainAutoRenew", "POST", "/", r)
proc disableDomainTransferLock*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DisableDomainTransferLock", "POST", "/", r)
proc enableDomainAutoRenew*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "EnableDomainAutoRenew", "POST", "/", r)
proc enableDomainTransferLock*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "EnableDomainTransferLock", "POST", "/", r)
proc getContactReachabilityStatus*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetContactReachabilityStatus", "POST", "/", r)
proc getDomainDetail*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetDomainDetail", "POST", "/", r)
proc getDomainSuggestions*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetDomainSuggestions", "POST", "/", r)
proc getOperationDetail*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetOperationDetail", "POST", "/", r)
proc listDomains*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListDomains", "POST", "/", r)
proc listOperations*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListOperations", "POST", "/", r)
proc listTagsForDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListTagsForDomain", "POST", "/", r)
proc registerDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RegisterDomain", "POST", "/", r)
proc renewDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RenewDomain", "POST", "/", r)
proc resendContactReachabilityEmail*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ResendContactReachabilityEmail", "POST", "/", r)
proc retrieveDomainAuthCode*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RetrieveDomainAuthCode", "POST", "/", r)
proc transferDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TransferDomain", "POST", "/", r)
proc updateDomainContact*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateDomainContact", "POST", "/", r)
proc updateDomainContactPrivacy*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateDomainContactPrivacy", "POST", "/", r)
proc updateDomainNameservers*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateDomainNameservers", "POST", "/", r)
proc updateTagsForDomain*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "UpdateTagsForDomain", "POST", "/", r)
proc viewBilling*(cl: Route53Domains, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ViewBilling", "POST", "/", r)
