# This file is autogenerated, do not modify
import json, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2016-06-02"
const awsApiMD_endpointPrefix* = "shield"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceAbbreviation* = "AWS Shield"
const awsApiMD_serviceFullName* = "AWS Shield"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "AWSShield_20160616"
const awsApiMD_uid* = "shield-2016-06-02"
defineClient(Shield)
proc createProtection*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateProtection", "POST", "/", r)
proc createSubscription*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateSubscription", "POST", "/", r)
proc deleteProtection*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteProtection", "POST", "/", r)
proc deleteSubscription*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteSubscription", "POST", "/", r)
proc describeAttack*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeAttack", "POST", "/", r)
proc describeProtection*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeProtection", "POST", "/", r)
proc describeSubscription*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeSubscription", "POST", "/", r)
proc getSubscriptionState*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "GetSubscriptionState", "POST", "/", r)
proc listAttacks*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListAttacks", "POST", "/", r)
proc listProtections*(cl: Shield, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ListProtections", "POST", "/", r)
