# This file is autogenerated, do not modify
import packedjson, asyncfutures
import utils/client
export client.new
const awsApiMD_apiVersion* = "2015-04-08"
const awsApiMD_endpointPrefix* = "workspaces"
const awsApiMD_jsonVersion* = "1.1"
const awsApiMD_protocol* = "json"
const awsApiMD_serviceFullName* = "Amazon WorkSpaces"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_targetPrefix* = "WorkspacesService"
const awsApiMD_uid* = "workspaces-2015-04-08"
defineClient(WorkSpaces)
proc createTags*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateTags", "POST", "/", r)
proc createWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "CreateWorkspaces", "POST", "/", r)
proc deleteTags*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DeleteTags", "POST", "/", r)
proc describeTags*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeTags", "POST", "/", r)
proc describeWorkspaceBundles*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeWorkspaceBundles", "POST", "/", r)
proc describeWorkspaceDirectories*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeWorkspaceDirectories", "POST", "/", r)
proc describeWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeWorkspaces", "POST", "/", r)
proc describeWorkspacesConnectionStatus*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "DescribeWorkspacesConnectionStatus", "POST", "/", r)
proc modifyWorkspaceProperties*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "ModifyWorkspaceProperties", "POST", "/", r)
proc rebootWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RebootWorkspaces", "POST", "/", r)
proc rebuildWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "RebuildWorkspaces", "POST", "/", r)
proc startWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StartWorkspaces", "POST", "/", r)
proc stopWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "StopWorkspaces", "POST", "/", r)
proc terminateWorkspaces*(cl: WorkSpaces, r: JsonNode): Future[JsonNode] = sendJsonRequest(cl, "TerminateWorkspaces", "POST", "/", r)
